id: P82257608
initial_creation_type: input
source_metadata:
  title: Karma Chakme Series
  language: de
  description: 'Texts by and about Karma Chakme (karma chags med, 1613–1678), also
    known as Rāga Asya, a Sanskritized version of his name which he often uses in
    his writings:'
  volume:
    1f85e54637dc4b918d835c3bcbbceb13:
      title: A Discourse on the Confession of Harmful Deeds Spoken by Yama Dharmarāja
        to Karma Chakme
      parent: Confession
    7653a5ee9535489f8e7a19c7e1516cd4:
      title: Brief Confession to the Earth Lords
      parent: Confession
    3e9ba8f11d704640b9c206e7f36008e5:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Gesar
    47e7495539f14a5c93ac090dd537e353:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Healing
    0629cf1bfcb741d8aea45907ab0d92a1:
      title: Prayer to Gyaltsen Tsemö Pung Gyen
      parent: Lungta
    1e4a1f4f67894b8f891e11ea9c2147e4:
      title: Prayer to the Lion of Speech
      parent: Mañjuśrī
    0800a569d0964bd59201c6f2412cab4a:
      title: A Concise Sang Offering to Tārā
      parent: Offering Rites
    432eb64531c84b4ba9a44d91e3ad7d42:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      parent: Offering Rites
    0e60787c14eb413fa2fd15bee3153b21:
      title: A Prayer to the Goddess Parṇaśavarī
      parent: Prayers
    1693276283b044d2af4c97ad64247693:
      title: Lamp Aspiration Prayer (from the Tsok Offering 'A Rain of Blessings')
      parent: Prayers
    a2a0d08eaea649ad80080c2a8fee2d11:
      title: Prayer for the Land of Great Bliss Practice
      parent: Prayers
    0688fd761e2649bfab4c78f5bd98bbb9:
      title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
      parent: Preliminary Practices
    aa959d6e54154e82bf5515ff5d6730f7:
      title: A Daily Practice of Buddha Akṣobhya
      parent: Sādhanas
    ba5f1f44fdea4d5281f45a6d4c38ec27:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Sādhanas
    5524336afda946e8aee167a648c4a76a:
      title: 'The Swift Steed of Garuḍa, King of Birds: An Instruction for Travelling
        to Sukhāvatī: A Visualization and Recitation of Uṣnīṣa-Sitātapatrā'
      parent: Sādhanas
    efe137126ef54c4f95d40f9f7bf2e0ea:
      title: Extensive Instructions on the Transference of Consciousness to the Land
        of Great Bliss
      parent: Transference of Consciousness
    1a145866034f42d4a160b4dd6c2d767a:
      title: Brief Dhāraṇī of Glorious Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-03-01T00:11:08.819567'
last_modified_at: '2022-03-01T00:11:08.819570'
